### ISSUE TITLE
About the model weight

### ISSUE THREAD

**Issue by LetheSec** [DUT-lujunyu/ToxiCN#3]
Hi,

Would you consider sharing the model weights?

**Comment by DUT-lujunyu** [comment]
Thank you for your interest in our work!
Because the model is relatively simple, we do not save the optimal parameters of the model. We would suggest downloading the original model parameters from huggingface and training according to the hyperparameters specified in the appendix of our paper.  You can employ early stopping mechanisms to retain the best model parameters. We believe that all results can be reproduced in this manner.
I hope this information is helpful to you. Please feel free to reach out if you have any further questions or need additional assistance.

**Comment by LetheSec** [comment]
OK, thank you for your reply.

**Comment by DUT-lujunyu** [comment]
您好，您的邮件已经收到，谢谢
